// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Orbito.Infrastructure.Data;

#nullable disable

namespace Orbito.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260322103323_AddProviderStripeCustomerId")]
    partial class AddProviderStripeCustomerId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Orbito.Domain.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DirectEmail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DirectFirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DirectLastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("InvitationToken")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("InvitationTokenExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("StripeCustomerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TenantId");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_Clients_TenantId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_Clients_UserId")
                        .HasFilter("[UserId] IS NOT NULL");

                    b.HasIndex("TenantId", "DirectEmail")
                        .HasDatabaseName("IX_Clients_TenantId_DirectEmail")
                        .HasFilter("DirectEmail IS NOT NULL");

                    b.ToTable("Clients", (string)null);
                });

            modelBuilder.Entity("Orbito.Domain.Entities.EmailNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NextRetryAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RecipientEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("RelatedEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RelatedEntityType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EmailNotifications");
                });

            modelBuilder.Entity("Orbito.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalPaymentId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ExternalTransactionId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("FailedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(100)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaymentMethodId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RefundReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefundedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TenantId");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("IX_Payments_ClientId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Payments_CreatedAt");

                    b.HasIndex("ExternalPaymentId")
                        .HasDatabaseName("IX_Payments_ExternalPaymentId")
                        .HasFilter("ExternalPaymentId IS NOT NULL");

                    b.HasIndex("ExternalTransactionId")
                        .IsUnique()
                        .HasDatabaseName("IX_Payments_ExternalTransactionId")
                        .HasFilter("ExternalTransactionId IS NOT NULL");

                    b.HasIndex("SubscriptionId")
                        .HasDatabaseName("IX_Payments_SubscriptionId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_Payments_TenantId");

                    b.HasIndex("SubscriptionId", "Status")
                        .IsUnique()
                        .HasDatabaseName("IX_Payments_SubscriptionId_Status_Unique")
                        .HasFilter("Status IN ('Pending', 'Processing')");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("IX_Payments_TenantId_Status");

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("Orbito.Domain.Entities.PaymentDiscrepancy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("AdditionalData")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("additional_data");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("detected_at");

                    b.Property<string>("ExternalPaymentId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("external_payment_id");

                    b.Property<decimal?>("OrbitoAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("orbito_amount");

                    b.Property<string>("OrbitoCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("orbito_currency");

                    b.Property<int?>("OrbitoStatus")
                        .HasColumnType("int")
                        .HasColumnName("orbito_status");

                    b.Property<Guid?>("PaymentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("payment_id");

                    b.Property<Guid>("ReconciliationReportId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("reconciliation_report_id");

                    b.Property<int>("Resolution")
                        .HasColumnType("int")
                        .HasColumnName("resolution");

                    b.Property<string>("ResolutionNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("resolution_notes");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("resolved_at");

                    b.Property<string>("ResolvedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("resolved_by");

                    b.Property<decimal?>("StripeAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("stripe_amount");

                    b.Property<string>("StripeCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("stripe_currency");

                    b.Property<string>("StripeStatus")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("stripe_status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("DetectedAt")
                        .HasDatabaseName("ix_payment_discrepancies_detected_at");

                    b.HasIndex("ExternalPaymentId")
                        .HasDatabaseName("ix_payment_discrepancies_external_payment_id");

                    b.HasIndex("PaymentId")
                        .HasDatabaseName("ix_payment_discrepancies_payment_id");

                    b.HasIndex("ReconciliationReportId")
                        .HasDatabaseName("ix_payment_discrepancies_report_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_payment_discrepancies_tenant_id");

                    b.HasIndex("TenantId", "Resolution")
                        .HasDatabaseName("ix_payment_discrepancies_tenant_resolution");

                    b.HasIndex("TenantId", "Type")
                        .HasDatabaseName("ix_payment_discrepancies_tenant_type");

                    b.ToTable("PaymentDiscrepancies", (string)null);
                });

            modelBuilder.Entity("Orbito.Domain.Entities.PaymentHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Details")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TenantId");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("IX_PaymentHistory_OccurredAt");

                    b.HasIndex("PaymentId")
                        .HasDatabaseName("IX_PaymentHistory_PaymentId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_PaymentHistory_Status");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_PaymentHistory_TenantId");

                    b.HasIndex("PaymentId", "OccurredAt")
                        .HasDatabaseName("IX_PaymentHistory_PaymentId_OccurredAt");

                    b.HasIndex("TenantId", "PaymentId")
                        .HasDatabaseName("IX_PaymentHistory_TenantId_PaymentId");

                    b.ToTable("PaymentHistory", (string)null);
                });

            modelBuilder.Entity("Orbito.Domain.Entities.PaymentMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastFourDigits")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .IsFixedLength(false);

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("ExpiryDate")
                        .HasDatabaseName("IX_PaymentMethods_ExpiryDate");

                    b.HasIndex("ClientId", "IsDefault")
                        .HasDatabaseName("IX_PaymentMethods_ClientId_IsDefault")
                        .HasFilter("[IsDefault] = 1");

                    b.HasIndex("TenantId", "ClientId")
                        .HasDatabaseName("IX_PaymentMethods_TenantId_ClientId");

                    b.HasIndex("Type", "CreatedAt")
                        .HasDatabaseName("IX_PaymentMethods_Type_CreatedAt");

                    b.ToTable("PaymentMethods", (string)null);
                });

            modelBuilder.Entity("Orbito.Domain.Entities.PaymentRetrySchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int")
                        .HasAnnotation("MaxValue", 10)
                        .HasAnnotation("MinValue", 1);

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ClientId");

                    b.Property<DateTime>("CreatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .IsUnicode(true)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("MaxAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(5)
                        .HasAnnotation("MaxValue", 10)
                        .HasAnnotation("MinValue", 1);

                    b.Property<DateTime>("NextAttemptAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PaymentId");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TenantId");

                    b.Property<DateTime>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("PaymentId")
                        .IsUnique()
                        .HasDatabaseName("IX_PaymentRetrySchedule_Payment_Active")
                        .HasFilter("[Status] IN ('Scheduled', 'InProgress')");

                    b.HasIndex("PaymentId", "Status")
                        .HasDatabaseName("IX_PaymentRetrySchedules_PaymentId_Status");

                    b.HasIndex("TenantId", "CreatedAt")
                        .HasDatabaseName("IX_PaymentRetrySchedules_TenantId_CreatedAt");

                    b.HasIndex("TenantId", "UpdatedAt")
                        .HasDatabaseName("IX_PaymentRetrySchedules_TenantId_UpdatedAt");

                    b.HasIndex("TenantId", "Status", "NextAttemptAt")
                        .HasDatabaseName("IX_PaymentRetrySchedules_TenantId_Status_NextAttemptAt")
                        .HasFilter("[Status] IN ('Scheduled', 'InProgress')");

                    b.HasIndex("TenantId", "ClientId", "Status", "NextAttemptAt")
                        .HasDatabaseName("IX_PaymentRetrySchedules_TenantId_ClientId_Status_NextAttemptAt")
                        .HasFilter("[Status] = 'Scheduled'");

                    b.ToTable("PaymentRetrySchedules", null, t =>
                        {
                            t.HasCheckConstraint("CK_PaymentRetrySchedules_AttemptNumber_NotExceedMax", "[AttemptNumber] <= [MaxAttempts]");

                            t.HasCheckConstraint("CK_PaymentRetrySchedules_AttemptNumber_Range", "[AttemptNumber] >= 1 AND [AttemptNumber] <= 10");

                            t.HasCheckConstraint("CK_PaymentRetrySchedules_MaxAttempts_Range", "[MaxAttempts] >= 1 AND [MaxAttempts] <= 10");

                            t.HasCheckConstraint("CK_PaymentRetrySchedules_NextAttemptAt_Future", "[NextAttemptAt] >= [CreatedAt]");
                        });
                });

            modelBuilder.Entity("Orbito.Domain.Entities.PaymentWebhookLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Metadata")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ReceivedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Status", "ReceivedAt")
                        .HasDatabaseName("IX_PaymentWebhookLogs_Status_ReceivedAt")
                        .HasFilter("[Status] = 'Failed'");

                    b.HasIndex("TenantId", "EventId")
                        .IsUnique()
                        .HasDatabaseName("IX_PaymentWebhookLogs_TenantId_EventId");

                    b.ToTable("PaymentWebhookLogs", (string)null);
                });

            modelBuilder.Entity("Orbito.Domain.Entities.PlatformPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FeaturesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("TrialDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(14);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_PlatformPlans_IsActive");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_PlatformPlans_Name");

                    b.HasIndex("SortOrder")
                        .HasDatabaseName("IX_PlatformPlans_SortOrder");

                    b.ToTable("PlatformPlans", (string)null);
                });

            modelBuilder.Entity("Orbito.Domain.Entities.Provider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActiveClientsCount")
                        .HasColumnType("int");

                    b.Property<string>("Avatar")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomDomain")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("StripeCustomerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubdomainSlug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TenantId");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SubdomainSlug")
                        .IsUnique()
                        .HasDatabaseName("IX_Providers_SubdomainSlug");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("IX_Providers_TenantId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_Providers_UserId")
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Providers", (string)null);
                });

            modelBuilder.Entity("Orbito.Domain.Entities.ProviderSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastNotificationSentAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("LastNotificationTier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("PaidUntil")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PlatformPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("TrialEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PlatformPlanId")
                        .HasDatabaseName("IX_ProviderSubscriptions_PlatformPlanId");

                    b.HasIndex("ProviderId")
                        .IsUnique()
                        .HasDatabaseName("IX_ProviderSubscriptions_ProviderId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_ProviderSubscriptions_Status");

                    b.HasIndex("TrialEndDate")
                        .HasDatabaseName("IX_ProviderSubscriptions_TrialEndDate");

                    b.HasIndex("Status", "TrialEndDate")
                        .HasDatabaseName("IX_ProviderSubscriptions_Status_TrialEndDate");

                    b.ToTable("ProviderSubscriptions", (string)null);
                });

            modelBuilder.Entity("Orbito.Domain.Entities.ReconciliationReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("AutoResolvedCount")
                        .HasColumnType("int")
                        .HasColumnName("auto_resolved_count");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("completed_at");

                    b.Property<int>("DiscrepanciesCount")
                        .HasColumnType("int")
                        .HasColumnName("discrepancies_count");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("time")
                        .HasColumnName("duration");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("error_message");

                    b.Property<int>("ManualReviewCount")
                        .HasColumnType("int")
                        .HasColumnName("manual_review_count");

                    b.Property<int>("MatchedPayments")
                        .HasColumnType("int")
                        .HasColumnName("matched_payments");

                    b.Property<int>("MismatchedPayments")
                        .HasColumnType("int")
                        .HasColumnName("mismatched_payments");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("datetime2")
                        .HasColumnName("period_end");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("datetime2")
                        .HasColumnName("period_start");

                    b.Property<DateTime>("RunDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("run_date");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.Property<int>("TotalPayments")
                        .HasColumnType("int")
                        .HasColumnName("total_payments");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_reconciliation_reports_tenant_id");

                    b.HasIndex("PeriodStart", "PeriodEnd")
                        .HasDatabaseName("ix_reconciliation_reports_period");

                    b.HasIndex("TenantId", "RunDate")
                        .HasDatabaseName("ix_reconciliation_reports_tenant_run_date");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_reconciliation_reports_tenant_status");

                    b.ToTable("ReconciliationReports", (string)null);
                });

            modelBuilder.Entity("Orbito.Domain.Entities.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalSubscriptionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsInTrial")
                        .HasColumnType("bit");

                    b.Property<DateTime>("NextBillingDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TenantId");

                    b.Property<DateTime?>("TrialEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("IX_Subscriptions_ClientId");

                    b.HasIndex("NextBillingDate")
                        .HasDatabaseName("IX_Subscriptions_NextBillingDate");

                    b.HasIndex("PlanId")
                        .HasDatabaseName("IX_Subscriptions_PlanId");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_Subscriptions_TenantId");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("IX_Subscriptions_TenantId_Status");

                    b.ToTable("Subscriptions", (string)null);
                });

            modelBuilder.Entity("Orbito.Domain.Entities.SubscriptionPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FeaturesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LimitationsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TenantId");

                    b.Property<int>("TrialDays")
                        .HasColumnType("int");

                    b.Property<int>("TrialPeriodDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_SubscriptionPlans_TenantId");

                    b.HasIndex("TenantId", "IsActive")
                        .HasDatabaseName("IX_SubscriptionPlans_TenantId_IsActive");

                    b.HasIndex("TenantId", "IsPublic")
                        .HasDatabaseName("IX_SubscriptionPlans_TenantId_IsPublic");

                    b.HasIndex("TenantId", "SortOrder")
                        .HasDatabaseName("IX_SubscriptionPlans_TenantId_SortOrder");

                    b.HasIndex("TenantId", "IsActive", "IsPublic")
                        .HasDatabaseName("IX_SubscriptionPlans_TenantId_IsActive_IsPublic");

                    b.ToTable("SubscriptionPlans", (string)null);
                });

            modelBuilder.Entity("Orbito.Domain.Entities.TeamMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("accepted_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("first_name");

                    b.Property<DateTime?>("InvitationExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("invitation_expires_at");

                    b.Property<string>("InvitationToken")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("invitation_token");

                    b.Property<DateTime>("InvitedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("invited_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<DateTime>("LastActiveAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_active_at");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("last_name");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("removed_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("role");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("tenant_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("InvitationToken")
                        .IsUnique()
                        .HasDatabaseName("IX_TeamMembers_InvitationToken")
                        .HasFilter("[invitation_token] IS NOT NULL");

                    b.HasIndex("InvitedAt")
                        .HasDatabaseName("IX_TeamMembers_InvitedAt");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_TeamMembers_IsActive");

                    b.HasIndex("Role")
                        .HasDatabaseName("IX_TeamMembers_Role");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_TeamMembers_TenantId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_TeamMembers_UserId");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique()
                        .HasDatabaseName("IX_TeamMembers_TenantId_Email");

                    b.HasIndex("TenantId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_TeamMembers_TenantId_UserId");

                    b.ToTable("TeamMembers", (string)null);
                });

            modelBuilder.Entity("Orbito.Domain.Identity.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TenantId");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("IX_AspNetRoles_NormalizedName")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_AspNetRoles_TenantId");

                    b.HasIndex("TenantId", "NormalizedName")
                        .HasDatabaseName("IX_AspNetRoles_TenantId_NormalizedName");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Platform Administrator - Full system access",
                            IsActive = true,
                            Name = "PlatformAdmin",
                            NormalizedName = "PLATFORMADMIN"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Service Provider - Manages clients and subscriptions",
                            IsActive = true,
                            Name = "Provider",
                            NormalizedName = "PROVIDER"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Client User - Manages own subscriptions and payments",
                            IsActive = true,
                            Name = "Client",
                            NormalizedName = "CLIENT"
                        });
                });

            modelBuilder.Entity("Orbito.Domain.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TenantId");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_AspNetUsers_Email");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("IX_AspNetUsers_NormalizedEmail");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("IX_AspNetUsers_NormalizedUserName")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_AspNetUsers_TenantId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Orbito.Domain.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Orbito.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Orbito.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Orbito.Domain.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Orbito.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Orbito.Domain.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Orbito.Domain.Entities.Client", b =>
                {
                    b.HasOne("Orbito.Domain.Entities.Provider", "Provider")
                        .WithMany("Clients")
                        .HasForeignKey("TenantId")
                        .HasPrincipalKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Orbito.Domain.Identity.ApplicationUser", "User")
                        .WithOne("ClientProfile")
                        .HasForeignKey("Orbito.Domain.Entities.Client", "UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Provider");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Orbito.Domain.Entities.Payment", b =>
                {
                    b.HasOne("Orbito.Domain.Entities.Client", "Client")
                        .WithMany("Payments")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Orbito.Domain.Entities.Subscription", "Subscription")
                        .WithMany("Payments")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.OwnsOne("Orbito.Domain.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("PaymentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("Currency");

                            b1.HasKey("PaymentId");

                            b1.ToTable("Payments");

                            b1.WithOwner()
                                .HasForeignKey("PaymentId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("Orbito.Domain.Entities.PaymentDiscrepancy", b =>
                {
                    b.HasOne("Orbito.Domain.Entities.Payment", "Payment")
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Orbito.Domain.Entities.ReconciliationReport", "ReconciliationReport")
                        .WithMany("Discrepancies")
                        .HasForeignKey("ReconciliationReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Payment");

                    b.Navigation("ReconciliationReport");
                });

            modelBuilder.Entity("Orbito.Domain.Entities.PaymentHistory", b =>
                {
                    b.HasOne("Orbito.Domain.Entities.Payment", "Payment")
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("Orbito.Domain.Entities.PaymentMethod", b =>
                {
                    b.HasOne("Orbito.Domain.Entities.Client", "Client")
                        .WithMany("PaymentMethods")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Orbito.Domain.Entities.PaymentRetrySchedule", b =>
                {
                    b.HasOne("Orbito.Domain.Entities.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Orbito.Domain.Entities.Payment", "Payment")
                        .WithMany()
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("Orbito.Domain.Entities.PlatformPlan", b =>
                {
                    b.OwnsOne("Orbito.Domain.ValueObjects.BillingPeriod", "BillingPeriod", b1 =>
                        {
                            b1.Property<Guid>("PlatformPlanId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Type")
                                .HasColumnType("int")
                                .HasColumnName("BillingPeriodType");

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("BillingPeriodValue");

                            b1.HasKey("PlatformPlanId");

                            b1.ToTable("PlatformPlans");

                            b1.WithOwner()
                                .HasForeignKey("PlatformPlanId");
                        });

                    b.OwnsOne("Orbito.Domain.ValueObjects.Money", "Price", b1 =>
                        {
                            b1.Property<Guid>("PlatformPlanId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("PriceAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("PriceCurrency");

                            b1.HasKey("PlatformPlanId");

                            b1.ToTable("PlatformPlans");

                            b1.WithOwner()
                                .HasForeignKey("PlatformPlanId");
                        });

                    b.Navigation("BillingPeriod")
                        .IsRequired();

                    b.Navigation("Price")
                        .IsRequired();
                });

            modelBuilder.Entity("Orbito.Domain.Entities.Provider", b =>
                {
                    b.HasOne("Orbito.Domain.Identity.ApplicationUser", "User")
                        .WithOne("Provider")
                        .HasForeignKey("Orbito.Domain.Entities.Provider", "UserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.OwnsOne("Orbito.Domain.ValueObjects.Money", "MonthlyRevenue", b1 =>
                        {
                            b1.Property<Guid>("ProviderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("MonthlyRevenueAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("MonthlyRevenueCurrency");

                            b1.HasKey("ProviderId");

                            b1.ToTable("Providers");

                            b1.WithOwner()
                                .HasForeignKey("ProviderId");
                        });

                    b.Navigation("MonthlyRevenue")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Orbito.Domain.Entities.ProviderSubscription", b =>
                {
                    b.HasOne("Orbito.Domain.Entities.PlatformPlan", "PlatformPlan")
                        .WithMany("ProviderSubscriptions")
                        .HasForeignKey("PlatformPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Orbito.Domain.Entities.Provider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlatformPlan");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Orbito.Domain.Entities.Subscription", b =>
                {
                    b.HasOne("Orbito.Domain.Entities.Client", "Client")
                        .WithMany("Subscriptions")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Orbito.Domain.Entities.SubscriptionPlan", "Plan")
                        .WithMany("Subscriptions")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Orbito.Domain.Entities.Provider", null)
                        .WithMany("Subscriptions")
                        .HasForeignKey("TenantId")
                        .HasPrincipalKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.OwnsOne("Orbito.Domain.ValueObjects.BillingPeriod", "BillingPeriod", b1 =>
                        {
                            b1.Property<Guid>("SubscriptionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("BillingPeriodType");

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("BillingPeriodValue");

                            b1.HasKey("SubscriptionId");

                            b1.ToTable("Subscriptions");

                            b1.WithOwner()
                                .HasForeignKey("SubscriptionId");
                        });

                    b.OwnsOne("Orbito.Domain.ValueObjects.Money", "CurrentPrice", b1 =>
                        {
                            b1.Property<Guid>("SubscriptionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("CurrentPriceAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("CurrentPriceCurrency");

                            b1.HasKey("SubscriptionId");

                            b1.ToTable("Subscriptions");

                            b1.WithOwner()
                                .HasForeignKey("SubscriptionId");
                        });

                    b.Navigation("BillingPeriod")
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("CurrentPrice")
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Orbito.Domain.Entities.SubscriptionPlan", b =>
                {
                    b.HasOne("Orbito.Domain.Entities.Provider", "Provider")
                        .WithMany("Plans")
                        .HasForeignKey("TenantId")
                        .HasPrincipalKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.OwnsOne("Orbito.Domain.ValueObjects.BillingPeriod", "BillingPeriod", b1 =>
                        {
                            b1.Property<Guid>("SubscriptionPlanId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("BillingPeriodType");

                            b1.Property<int>("Value")
                                .HasColumnType("int")
                                .HasColumnName("BillingPeriodValue");

                            b1.HasKey("SubscriptionPlanId");

                            b1.ToTable("SubscriptionPlans");

                            b1.WithOwner()
                                .HasForeignKey("SubscriptionPlanId");
                        });

                    b.OwnsOne("Orbito.Domain.ValueObjects.Money", "Price", b1 =>
                        {
                            b1.Property<Guid>("SubscriptionPlanId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("PriceAmount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnName("PriceCurrency");

                            b1.HasKey("SubscriptionPlanId");

                            b1.ToTable("SubscriptionPlans");

                            b1.WithOwner()
                                .HasForeignKey("SubscriptionPlanId");
                        });

                    b.Navigation("BillingPeriod")
                        .IsRequired();

                    b.Navigation("Price")
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Orbito.Domain.Entities.TeamMember", b =>
                {
                    b.HasOne("Orbito.Domain.Entities.Provider", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .HasPrincipalKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Orbito.Domain.Identity.ApplicationRole", b =>
                {
                    b.HasOne("Orbito.Domain.Entities.Provider", "Provider")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .HasPrincipalKey("TenantId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Orbito.Domain.Entities.Client", b =>
                {
                    b.Navigation("PaymentMethods");

                    b.Navigation("Payments");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("Orbito.Domain.Entities.PlatformPlan", b =>
                {
                    b.Navigation("ProviderSubscriptions");
                });

            modelBuilder.Entity("Orbito.Domain.Entities.Provider", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("Plans");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("Orbito.Domain.Entities.ReconciliationReport", b =>
                {
                    b.Navigation("Discrepancies");
                });

            modelBuilder.Entity("Orbito.Domain.Entities.Subscription", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Orbito.Domain.Entities.SubscriptionPlan", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("Orbito.Domain.Identity.ApplicationUser", b =>
                {
                    b.Navigation("ClientProfile");

                    b.Navigation("Provider");
                });
#pragma warning restore 612, 618
        }
    }
}
