using FluentAssertions;
using Microsoft.Extensions.Logging;
using Moq;
using Orbito.Application.Common.Interfaces;
using Orbito.Application.Features.TeamMembers.Commands.AcceptInvitation;
using Orbito.Domain.Entities;
using Orbito.Domain.Enums;
using Orbito.Domain.Errors;
using Orbito.Domain.Interfaces;
using Orbito.Tests.Helpers;
using Xunit;

namespace Orbito.Tests.Application.Features.TeamMembers.Commands.AcceptInvitation;

[Trait("Category", "Unit")]
public class AcceptInvitationCommandHandlerTests : BaseTestFixture
{
    private readonly Mock<ITeamMemberRepository> _teamMemberRepositoryMock;
    private readonly Mock<IUserContextService> _userContextServiceMock;
    private readonly Mock<ILogger<AcceptInvitationCommandHandler>> _loggerMock;
    private readonly AcceptInvitationCommandHandler _handler;
    private readonly Guid _testUserId = Guid.NewGuid();
    private const string TestEmail = "invited@example.com";

    public AcceptInvitationCommandHandlerTests()
    {
        _teamMemberRepositoryMock = new Mock<ITeamMemberRepository>();
        _userContextServiceMock = new Mock<IUserContextService>();
        _loggerMock = new Mock<ILogger<AcceptInvitationCommandHandler>>();

        _handler = new AcceptInvitationCommandHandler(
            _teamMemberRepositoryMock.Object,
            _userContextServiceMock.Object,
            UnitOfWorkMock.Object,
            _loggerMock.Object);

        // Default setup
        _userContextServiceMock.Setup(x => x.GetCurrentUserId()).Returns(_testUserId);
        _userContextServiceMock.Setup(x => x.GetCurrentUserEmail()).Returns(TestEmail);
    }

    [Fact]
    public async Task Handle_ValidToken_ShouldActivateTeamMember()
    {
        // Arrange
        var teamMember = new TeamMember(
            TestTenantId,
            Guid.NewGuid(),
            TeamMemberRole.Member,
            TestEmail);

        // Use the actual invitation token generated by TeamMember
        var token = teamMember.InvitationToken!;
        var command = new AcceptInvitationCommand { Token = token };

        _teamMemberRepositoryMock
            .Setup(x => x.GetByInvitationTokenAsync(token, It.IsAny<CancellationToken>()))
            .ReturnsAsync(teamMember);

        _teamMemberRepositoryMock
            .Setup(x => x.UpdateAsync(It.IsAny<TeamMember>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync((TeamMember tm, CancellationToken ct) => tm);

        // Act
        var result = await _handler.Handle(command, CancellationToken.None);

        // Assert
        result.Should().NotBeNull();
        result.IsSuccess.Should().BeTrue();
        result.Value.Should().NotBeNull();

        _teamMemberRepositoryMock.Verify(
            x => x.UpdateAsync(It.Is<TeamMember>(tm => tm.HasAcceptedInvitation), It.IsAny<CancellationToken>()),
            Times.Once);
        VerifySaveChangesCalledOnce();
    }

    [Fact]
    public async Task Handle_ExpiredToken_ShouldReturnFailure()
    {
        // Arrange
        var token = "expired-token";
        var command = new AcceptInvitationCommand { Token = token };

        var teamMember = new TeamMember(
            TestTenantId,
            Guid.NewGuid(),
            TeamMemberRole.Member,
            TestEmail);

        // Simulate expired invitation by setting expiration date in the past
        typeof(TeamMember).GetProperty("InvitationExpiresAt")!.SetValue(teamMember, DateTime.UtcNow.AddDays(-1));

        _teamMemberRepositoryMock
            .Setup(x => x.GetByInvitationTokenAsync(token, It.IsAny<CancellationToken>()))
            .ReturnsAsync(teamMember);

        // Act
        var result = await _handler.Handle(command, CancellationToken.None);

        // Assert
        result.Should().NotBeNull();
        result.IsSuccess.Should().BeFalse();
        result.Error.Should().Be(DomainErrors.TeamMember.InvitationExpired);

        _teamMemberRepositoryMock.Verify(
            x => x.UpdateAsync(It.IsAny<TeamMember>(), It.IsAny<CancellationToken>()),
            Times.Never);
        VerifySaveChangesNeverCalled();
    }

    [Fact]
    public async Task Handle_InvalidToken_ShouldReturnFailure()
    {
        // Arrange
        var token = "invalid-token";
        var command = new AcceptInvitationCommand { Token = token };

        _teamMemberRepositoryMock
            .Setup(x => x.GetByInvitationTokenAsync(token, It.IsAny<CancellationToken>()))
            .ReturnsAsync((TeamMember?)null);

        // Act
        var result = await _handler.Handle(command, CancellationToken.None);

        // Assert
        result.Should().NotBeNull();
        result.IsSuccess.Should().BeFalse();
        result.Error.Should().Be(DomainErrors.TeamMember.NotFound);

        VerifySaveChangesNeverCalled();
    }

    [Fact]
    public async Task Handle_AlreadyActivated_ShouldReturnFailure()
    {
        // Arrange
        var token = "already-used-token";
        var command = new AcceptInvitationCommand { Token = token };

        var teamMember = new TeamMember(
            TestTenantId,
            Guid.NewGuid(),
            TeamMemberRole.Member,
            TestEmail);

        // Simulate already accepted invitation
        teamMember.AcceptInvitation(_testUserId);

        _teamMemberRepositoryMock
            .Setup(x => x.GetByInvitationTokenAsync(token, It.IsAny<CancellationToken>()))
            .ReturnsAsync(teamMember);

        // Act
        var result = await _handler.Handle(command, CancellationToken.None);

        // Assert
        result.Should().NotBeNull();
        result.IsSuccess.Should().BeFalse();
        result.Error.Should().Be(DomainErrors.TeamMember.AlreadyAccepted);

        VerifySaveChangesNeverCalled();
    }

    [Fact]
    public async Task Handle_EmptyToken_ShouldReturnFailure()
    {
        // Arrange
        var command = new AcceptInvitationCommand { Token = "" };

        // Act
        var result = await _handler.Handle(command, CancellationToken.None);

        // Assert
        result.Should().NotBeNull();
        result.IsSuccess.Should().BeFalse();
        result.Error.Message.Should().Contain("Invitation token");

        _teamMemberRepositoryMock.Verify(
            x => x.GetByInvitationTokenAsync(It.IsAny<string>(), It.IsAny<CancellationToken>()),
            Times.Never);
    }

    [Fact]
    public async Task Handle_NoAuthenticatedUser_ShouldReturnFailure()
    {
        // Arrange
        var token = "valid-token";
        var command = new AcceptInvitationCommand { Token = token };

        _userContextServiceMock.Setup(x => x.GetCurrentUserId()).Returns((Guid?)null);

        // Act
        var result = await _handler.Handle(command, CancellationToken.None);

        // Assert
        result.Should().NotBeNull();
        result.IsSuccess.Should().BeFalse();
        result.Error.Should().Be(DomainErrors.General.Unauthorized);

        _teamMemberRepositoryMock.Verify(
            x => x.GetByInvitationTokenAsync(It.IsAny<string>(), It.IsAny<CancellationToken>()),
            Times.Never);
    }

    [Fact]
    public async Task Handle_EmailMismatch_ShouldReturnFailure()
    {
        // Arrange
        var teamMember = new TeamMember(
            TestTenantId,
            Guid.NewGuid(),
            TeamMemberRole.Member,
            "different@example.com"); // Different email

        // Use the actual invitation token generated by TeamMember
        var token = teamMember.InvitationToken!;
        var command = new AcceptInvitationCommand { Token = token };

        _teamMemberRepositoryMock
            .Setup(x => x.GetByInvitationTokenAsync(token, It.IsAny<CancellationToken>()))
            .ReturnsAsync(teamMember);

        _userContextServiceMock.Setup(x => x.GetCurrentUserEmail()).Returns(TestEmail);

        // Act
        var result = await _handler.Handle(command, CancellationToken.None);

        // Assert
        result.Should().NotBeNull();
        result.IsSuccess.Should().BeFalse();
        result.Error.Should().Be(DomainErrors.General.Unauthorized);

        VerifySaveChangesNeverCalled();
    }
}
